### ISSUE TITLE
Payment issue on WP4.8.2 with WC2.6.4

### ISSUE THREAD

**Issue by RC-Klub** [szelpe/woocommerce-barion#15]
2017/11/06 18:14:28 [error] 1423#1423: *14286 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method WC_Order::get_id() in /var/www/htdocs/wp-content/plugins/pay-via-barion-for-woocommerce/includes/class-wc-gateway-barion-request.php:15
Stack trace:
#0 /var/www/htdocs/wp-content/plugins/pay-via-barion-for-woocommerce/class-wc-gateway-barion.php(126): WC_Gateway_Barion_Request->prepare_payment(Object(WC_Order))
#1 /var/www/htdocs/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(663): WC_Gateway_Barion->process_payment(108267)
#2 /var/www/htdocs/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(472): WC_Checkout->process_checkout()
#3 /var/wwwhtdocs/wp-includes/class-wp-hook.php(298): WC_AJAX::checkout('')
#4 /var/www/htdocs/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#5 /var/www/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 /var/www/htdocs/wp-content/plugins/woocommerce/includes/class-wc-aj" while reading response header from upstream, client: 10.10.10.10, server: mydomain.com, request: "POST /penztar/?wc-ajax=checkout HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "www.mydomain.com", referrer: "https://www.mydomain.com/penztar/"

**Comment by szelpe** [comment]
WC >= 3.0.0 is required

**Comment by RC-Klub** [comment]
sad :(
Change log on official WP plugins page (not shown wc 3.0 requirement)
BTW i rollbacked to 1.0.3:


1.3.1

Ignoring Barion callback in case the payment was already completed.
1.3.0

Changed the text domain to match the wordpress.org slug.
1.2.0

Added option to select the order state after a successful payment
Fixed dropdown heigh issue
1.1.0

Updated Barion Library to the latest version
Added supported languages (DE, SL, SK, FR)
Substituted deprecated function calls with current ones
1.0.2

Updated Barion Library to the latest version

**Comment by szelpe** [comment]
Thanks for pointing out. Why are you using such an outdated version of WC?
