### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by wargaa** [szelpe/woocommerce-barion#18]
A webáruházamban lévő hibához szeretnék segítséget kérni. A szóban forgó bővítménnyel tökéletesen működött 2016 óta a webáruházam, de most valamiért a Barion fizetési mód kiválasztása után nem dobja tovább a vásárlót a Barion oldalára, Internal Server Error hibát ír ki. Vajon mi lehet a probléma? Előre is köszönöm a segítséget!

**Comment by szelpe** [comment]
Szia! Küld el kérlek a Wordpress, WooCommerce, és a Barion Payment Gateway for WooCommerce pluginek verzióit. Emellett kérlek nézd meg, hogy van-e valami hiba a WooCommerce logjában (WooCommerce > Állapot > Naplók menüpont), valamint, hogy van-e hiba a webszerverek hibanaplójában.

**Comment by wargaa** [comment]
*Szia!Verziók:*

Wordpress 4.9.4.
WooCommerce 2.6.8.
Barion Payment  Gateway for WooCommerce plugin 2.1.0.

*WooCommerce napló hibák:*

WC oldalak
Üzlet főoldal <https://babavaros.hu/wp-admin/admin.php?page=wc-status>:  Az
oldal ID-ja beállítva, de az oldal nem létezik.
Sablonok
Felülírások (WooCommerce):
oxy-child/woocommerce/single-product/product-image.php verzió *2.0.14* elavult.
A legutóbbi verzió száma 2.6.3,
oxy-child/woocommerce/single-product/product-thumbnails.php verzió
*2.3.0* elavult.
A legutóbbi verzió száma 2.6.3,



A webszerverek hibanaplóját nem tudom hogy tudom megnézni. Tudsz ebben
segíteni?

A WooCommerce régebbi verziója okozhatja ezt a hibát? Azért nem lett
frissítve, mert több minden elállítódik az oldalon.

Előre is köszönöm!

Üdv.
Varga Andrea


2018-03-04 15:16 GMT+01:00 Szél Péter <notifications@github.com>:

**Comment by szelpe** [comment]
Szia!

Igen, nagyon régi a WooCommerce plugined, legalább 3.0.0-s verzió kell, hogy működjön a Barion plugin legfrissebb verziója.

**Comment by wargaa** [comment]
Buta kérdés, de az nem működik, hogy átmenetileg visszaállítsam a Barion
plugin régebbi verzióját, hogy működjön a fizetés, amíg felkészítem az
oldalt, hogy ne essen szét, ha frissítem a Woocommerce-t a legfrissebb
verzióra? Ha működik hol érem el a régebbi verziót?

2018-03-04 15:42 GMT+01:00 Szél Péter <notifications@github.com>:

**Comment by szelpe** [comment]
Szia! Megpróbálhatsz visszaállni az 1.0.3 verzióra, itt elérheted: https://downloads.wordpress.org/plugin/pay-via-barion-for-woocommerce.1.0.3.zip

Ez egyáltalán nem támogatott megoldás, vagy működik, vagy nem.

**Comment by wargaa** [comment]
Köszönöm szépen a segítséget!

2018. márc. 4. du. 3:51 ezt írta ("Szél Péter" <notifications@github.com>):

Szia! Megpróbálhatsz visszaállni az 1.0.3 verzióra, itt elérheted:
https://downloads.wordpress.org/plugin/pay-via-barion-for-
woocommerce.1.0.3.zip

Ez egyáltalán nem támogatott megoldás, vagy működik, vagy nem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/szelpe/woocommerce-barion/issues/18#issuecomment-370235030>,
or mute the thread
