### ISSUE TITLE
Reoccouring payments

### ISSUE THREAD

**Issue by smil2k** [szelpe/woocommerce-barion#20]
Hi,

Did you considered supporting reoccouring payments?

https://docs.woocommerce.com/document/subscriptions/develop/payment-gateway-integration/

Cheers,

Tamas

**Comment by szelpe** [comment]
Hi,

You can purchase a plugin from me which enhances the Barion plugin to support the Subscriptions extension. Please contact me at szelpeter@szelpeter.hu if you're interested.

Regards,
Peter
