### ISSUE TITLE
Pressing the browser's back button on the Barion payment page leaves the order in an inconsistent state

### ISSUE THREAD

**Issue by gcsecsey** [szelpe/woocommerce-barion#28]
If a customer:
- selects the Barion option from the payment options
- and proceeds to the Barion payment page
- and presses the browser's back button
They get redirected to the `/checkout` page without request parameters, as if they're visiting it for the first time. Meanwhile, the payment window on the Barion session is open for 30 minutes. If the customer then chooses another payment method and checks out successfully with that, the order gets cancelled automatically via the Barion callback. I have a couple of examples of this happening on my page:
![image](https://user-images.githubusercontent.com/11555574/53685429-d5fbbe00-3d1a-11e9-80f0-8a6854fcfe3b.png)

Unfortunately, beside informing the customers not to use the browser's navigation buttons while on the Barion page, I cannot really do anything about it. I think an additional query parameter (like a nonce) should be used when visiting the `/checkout` page in order to be able to detect if the customer is visiting the page while the payment window is still open.

**Comment by szelpe** [comment]
How would this query parameter work?

**Comment by gcsecsey** [comment]
Not completely sure, as I'm quite unfamiliar with the Woocommerce
checkout's inner workings, but I think different cases should be separated,
as a backward navigation is clearly not equivalent if the user is coming
from the Woocommerce thank you page (albeit this being potentially just as
confusing from a UX standpoint), and the Barion payment page. Is there any
way in Barion's API to detect and/or act upon a user pressing the browser
back button while on the payment screen? I think that would be the most
straightforward, most convenient way to detect such a case.

**Comment by szelpe** [comment]
I don't think there is an API for the. A possible solution for this situation is to ignore the Barion callback if the order is in "On-Hold" (e.g. waiting for bank transfer)

**Comment by gcsecsey** [comment]
That'be a very good and easy to implement workaround, thank you. I'll test it on my site then would gladly make a PR for it, if that's OK by you.

**Comment by szelpe** [comment]
Thanks, go ahead, I'm looking forward to it.

**Comment by szelpe** [comment]
This would be an ideal place of that: https://github.com/szelpe/woocommerce-barion/blob/master/includes/class-wc-gateway-barion-ipn-handler.php#L37

**Comment by gcsecsey** [comment]
Thanks, that will indeed be great! I initiated a test order on my site, but now I have to wait 30 minutes for the callback to occur. 😄
