### ISSUE TITLE
Bank buttons

### ISSUE THREAD

**Issue by slavicek-milos** [szelpe/woocommerce-barion#33]
Hello, I have installed your plugin on e-shop and the button is not displayed by bank transfer after approval by Barion.
And it goes somewhere to change the name of the button "proceed to Barion" to Czech "zaplatit"?

Thank You

Slavíček Miloš

**Comment by slavicek-milos** [comment]
Barion asked if we have met the technical requirements: [https://docs.barion.com/Payment_Buttons](https://docs.barion.com/Payment_Buttons) 
And unfortunately I don't know

**Comment by slavicek-milos** [comment]
Sorry for my English, I use google translator

**Comment by szelpe** [comment]
This is now fixed in version above 3.0.0
