### ISSUE TITLE
Release 3.0.0 (and 3.0.1) fails in PreparePayment with "The field Region must be a string or array type with a minimum length of '2'."

### ISSUE THREAD

**Issue by mark-plukkido** [szelpe/woocommerce-barion#37]
After updating the plugin to the 3.x.x version payment requests fail completely and the following error shows up in the logs:

`09-02-2019 @ 20:19:33 - PreparePayment failed. Errors array: [{"ErrorCode":"ModelValidationError","Title":"Model Validation Error","Description":"The field Region must be a string or array type with a minimum length of '2'."},{"ErrorCode":"ModelValidationError","Title":"Model Validation Error","Description":"The field Region must be a string or array type with a minimum length of '2'."}]`

@szelpe as I'm sure you're already aware, Barion won't work without the new library and 3D Secure after mid-September, so this is somewhat of an urgent issue. Thank you for taking a look at it and thank you for the module.

**Comment by szelpe** [comment]
The new version of the plugin uses the newest version of the Barion library and supports 3D Secure payments. The above error occurs when you don't have a shipping address, this will be fixed in 3.0.2

**Comment by mark-plukkido** [comment]
Thanks. We have shipping addresses for all the orders which failed with this error, but I suppose you refer to the missing field 'region', which are not required in Hungarian shipping addresses.

**Comment by szelpe** [comment]
> Thanks. We have shipping addresses for all the orders which failed with this error, but I suppose you refer to the missing field 'region', which are not required in Hungarian shipping addresses.

Thanks, I wasn't aware of the fact that region is not required in Hungary, that actually makes things harder a bit.

**Comment by mark-plukkido** [comment]
I'm sorry, I was not very clear in my communication. Region IS a required field in WooCommerce. However people usually does not ask for the region in Hungary as you may know, so many users (including us), just disable that field. We made the mistake of disabling it from the template (PHP).

Anyway, now that we put the region field back on the order form, it works with the new version (3.0.1). Thanks!

**Comment by szelpe** [comment]
Ok, in the next version of the plugin I'll fix this issue and then you can disable the county field again.

**Comment by balintjoe-1985** [comment]
Hi @szelpe! Do you know when will arive the nex version?

**Comment by szelpe** [comment]
Yes, very soon

**Comment by szelpe** [comment]
This is now fixed in version above 3.0.0

**Comment by lezsakdomi** [comment]
Well, experienced in 3.0.3. I really hope I just misread something.

**Comment by lezsakdomi** [comment]
Got finer details:
- "The country subdivision code (state or county) of the recipient address in ISO-3166-2 format" (quote from the api docs)
- I were able to solve it by setting `Region` to `null` instead of the acquired data unconditionally on lines https://github.com/szelpe/woocommerce-barion/blob/9e597c52405264508c55d6ab951d958d97a4c76c/includes/class-wc-gateway-barion-request.php#L227 and https://github.com/szelpe/woocommerce-barion/blob/9e597c52405264508c55d6ab951d958d97a4c76c/includes/class-wc-gateway-barion-request.php#L227
- The issue only applies when the county is not selected from a list but entered manually

**Comment by szelpe** [comment]
If you let your users enter county manually is a different case then the issue above (where the county field is hidden)
