### ISSUE TITLE
More advanced callback handling

### ISSUE THREAD

**Issue by BGERI95** [szelpe/woocommerce-barion#38]
Van-e lehetőség arra, hogy javítsuk a Barion callback kezelését? Gondolok itt arra, hogy a rendelés állapota sikeres fizetés után ne csak "processing", hanem "completed" is lehessen ha automatikus módban vagyunk.

Illetve nem világos, hogy mi történik, ha az ide vonatkozó beállítási lehetőséget ("Rendelés állapota a fizetés után") fixen "completed"-re állítom. Ebben az esetben a sikertelen fizetés is teljesített rendelést eredményez?

**Comment by szelpe** [comment]
Igen, pontosan erre való ez a beállítás, amit írtál.

**Comment by szelpe** [comment]
Sikertelen rendelés után természetesen nem lesz teljesített a rendelés semmilyen beállítás esetén sem.

**Comment by BGERI95** [comment]
Köszönöm, így érthető a funkció.
A fordítási fájlok és a kód összevetése után javasolnám a következő fordítás módosítását:

ENG: Choose the status of the order after successful Barion payment.
HU: Kiválaszthatod, hogy **sikeres** fizetés után milyen állapotba kerüljön a rendelés.

**Comment by szelpe** [comment]
Szuper, köszi
