### ISSUE TITLE
Error processing checkout. Please try again.

### ISSUE THREAD

**Issue by VisioDesign** [szelpe/woocommerce-barion#39]
Hello,

I get error message when I clicking to Pay with Barion (order placement).
Error message: "Error processing checkout. Please try again."

Error log: [04-Feb-2020 10:58:38 UTC] PHP Notice:  Undefined property: WC_Gateway_Barion_Request::$is_prepared in /home/uhlarada/sporttherapy.hu/wp-content/plugins/pay-via-barion-for-woocommerce/class-wc-gateway-barion.php on line 210

The php version 7.3, cURL is active.
Other payment solutions is working (example: Paypal)

I tried turn off any other plugin on website, just Woocommerce and Barion plugin active. Unfortunelly it didn't work also. 

The website: https://sporttherapy.hu/
For example product: https://sporttherapy.hu/treningek/gerinc-trening/

Please help me. 
Thanks,

**Comment by szelpe** [comment]
Hi,

Can you please check the WooCommerce log (WooCommerce > Status > Log)

**Comment by VisioDesign** [comment]
The last log: 

01-04-2020 @ 19:41:01 - PreparePayment failed. Errors array: [{"ErrorCode":"AuthenticationFailed","Title":"User authentication failed.","Description":"The login information provided is incorrect. There is no such user in the system or the password is incorrect."}]

The Barion approved and activated the account in december. They don't see a mistake now.

**Comment by szelpe** [comment]
So you're not using the correct email address or password. I've checked your website and it's set to test mode, so make sure to use the credentials for the test Barion site (https://test.barion.com) and not the real one.

**Comment by VisioDesign** [comment]
Thanks. Sorry. Gave me the wrong email address from client. (I tried live and test mode also).
