### ISSUE TITLE
Barion Fizetési hiba

### ISSUE THREAD

**Issue by Marton88** [szelpe/woocommerce-barion#41]
Sziasztok ,

A következő problémában szeretnék segítséget kérni.

Egy sima kis egyszerü weboldalt készítettem ismerösömnek és Barion Fizetést szeretnék az oldalra .
A barion oldaláról megtörtén a hítelesítés mindent rendben találtak és a fizetőhely aktív állapotba lépet. 
Viszont az oldalon ha a barion fizetési lehetőséget választom akkor " hiba a rendelés feldolgozása során " üzenetet kapom .

A Crome Nework monitoring a következőt mutatja : 
result: "failure", messages: "", refresh: false, reload: false}
messages: ""
refresh: false
reload: false
result: "failure"

Weboldal : https://mrpocak.com/

Barion adatrok mindenhol stimmelnek .

**Comment by szelpe** [comment]
Szia,

Nézd meg kérlek mi van a WooCommerce > Állapot > Naplók alatt.

**Comment by Marton88** [comment]
07-08-2020 @ 08:52:43 - PreparePayment failed. Errors array: [{"ErrorCode":"InvalidUser","Title":"Invalid user","Description":"Invalid user(lantosberni@gmail.com)!"}]

**Comment by Marton88** [comment]
Köszönöm :) Igy már egyértelmü lett :D
