### ISSUE TITLE
PreparePayment failed

### ISSUE THREAD

**Issue by trieblistvan** [szelpe/woocommerce-barion#52]
Hi,

On checkout page I got the error: "Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra."
...?wc-ajax=checkout response:
{"result":"failure","messages":"","refresh":false,"reload":false}

barion log:
PreparePayment failed. Errors array: []

WooCommerce logs nothing. Order is created (payment pending status), but user does not get redirected to barion.

WP: 5.4.4
Woo: 3.5.10
PHP: 7.4

I think Woo got updated automatically (previous version: 3.5.9) and payment fails since then. 

Thanks,
Istvan

**Comment by trieblistvan** [comment]
Szia!

A tarhely.eu -nál.  Közben még annyit találtam, hogy a https://api.barion.com/v2/Payment/Start hívásra egy html file jön válaszként, kb:

"Please wait...
We are checking your browser... api.barion.com

Please stand by, while we are checking your browser...
Why do I have to complete a CAPTCHA?

Completing the CAPTCHA proves you are a human and gives you temporary access to the web property.
What can I do to prevent this in the future?

If you are on a personal connection, like at home, you can run an anti-virus scan on your device to make sure it is not infected with malware.

If you are at an office or shared network, you can ask the network administrator to run a scan across the network looking for misconfigured or infected devices."

malware?

bejelentettem a barion-nál is  - meg a tárhely szolgáltatónál is.

Köszönöm!
István

**Comment by futyko** [comment]
@trieblistvan Nálunk a Cloudflare letiltotta a tárhelyszolgáltató szerverét. Az általad említett html válasz is erre utal. A Barion-tól kértük, hogy tegyék az IP-t whitelist-re, azóta minden jól működik. Minden bizonnyal nálad is ez oldotta meg a dolgot. 
Ja igen, @szelpe segített ezt kinyomozni, akinek ezúton is még egyszer nagyon köszönöm!

**Comment by trieblistvan** [comment]
> @trieblistvan Nálunk a Cloudflare letiltotta a tárhelyszolgáltató szerverét. Az általad említett html válasz is erre utal. A Barion-tól kértük, hogy tegyék az IP-t whitelist-re, azóta minden jól működik. Minden bizonnyal nálad is ez oldotta meg a dolgot. Ja igen, @szelpe segített ezt kinyomozni, akinek ezúton is még egyszer nagyon köszönöm!

OK, én is köszi @szelpe !!!
