### ISSUE TITLE
 Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra

### ISSUE THREAD

**Issue by futyko** [szelpe/woocommerce-barion#53]
Hi! 

Your kind support is greatly appreciated, as I am totally clueless.

wp: 5.8.4
woo: 6.3.1
php: 7.4.28

We are getting the subject error **on desktop** (Hiba a fizetés feldolgozásakor. Kérlek, próbáld újra). An order is being created with wc-pending status and later canceled. It is followed by an empty log:

04-19-2022 @ 14:05:03 - PreparePayment failed. Errors array: []

**On mobile**, the webshop redirects to barion site, but after a successful payment (confirmed by barion), wp gets no answer from barion, and the order gets canceled due to time limit reached. It also has an empty log, so I have nowhere to start investigating this issue:

`04-18-2022 @ 10:11:22 - Payment failed. Payment details: {"PaymentId":"","PaymentRequestId":"","OrderNumber":"","POSId":"","POSName":"","POSOwnerEmail":"","Status":"","PaymentType":"","FundingSource":"","FundingInformation":{"BankCard":{"MaskedPan":"","BankCardType":"","ValidThruYear":"","ValidThruMonth":""},"AuthorizationCode":""},"AllowedFundingSources":"","GuestCheckout":"","CreatedAt":"","ValidUntil":"","CompletedAt":"","ReservedUntil":"","Total":0,"Currency":"","Transactions":[],"RecurrenceResult":"","SuggestedLocale":"","FraudRiskScore":0,"RedirectUrl":"","CallbackUrl":"","RecurrenceType":"","TraceId":"","Errors":[],"RequestSuccessful":false}`

**Comment by omnitechinfo** [comment]
Sziasztok,

A probléma szó szerint ugyanaz, mint @futyko -nál.
woo:6.3.1
wp: 5.9.3
php: 7.4.28

Várnánk válaszotok.

**Comment by omnitechinfo** [comment]
185.111.89.218
Ugyanaz

**Comment by omnitechinfo** [comment]
Megkerestem a Tárhelyparkot és azt mondták náluk nincs semmi hiba...

**Comment by omnitechinfo** [comment]
@futyko Hosszas nyomozás után kiderült, hogy a tárhelyszolgáltatónál van a hiba. Már legalább 3 webshop jelezte (velünk együtt), ezt a problémát.
Dolgoznak a megoldásán, egyelőre ők sem tudják mi lehet a probléma.
Úgy tűnik a szerverük tiltja valami miatt a bariontól bejövő adatokat.

Alternatív megoldás lehet ideiglenesen egy másik fizetési megoldás integrálása.
@szelpe 
Ha addig rá tudnátok nézni a pluginra, az jó lenne. Kérték is, ha kapunk tőletek valami jelzést, akkor küldjük át nekik.
Köszönöm.

**Comment by futyko** [comment]
A tárhelyszolgáltatót tiltotta a Cloudflare, de ez azóta megoldódott. 

@szelpe segített kinyomozni a hiba okát. Hálás köszönet érte!

**Comment by omnitechinfo** [comment]
@futyko @szelpe Köszönöm én is. Mi közben kértük a tárhelyszolgáltatót, hogy kötöztesse át egy másik szerverére a honlapot, ami nem volt tiltva. :)
