### ISSUE TITLE
A régi cacert.pem Curl #60 SSL hibát okoz

### ISSUE THREAD

**Issue by mtx33q** [szelpe/woocommerce-barion#69]
Jelenleg a plugin a "barion-library"-be égetett cacert.pem fájt használja, ami március 31-én megváltozott. Jelenleg minden barionos fizetés ebbe a hibába fut:

`PreparePayment failed. Errors array: [{"ErrorCode":"CURL_ERROR","Title":"CURL Error #60","Description":"SSL certificate problem: certificate has expired","HappenedAt":"","AuthData":"","EndPoint":"","PaymentId":""}]`

A cert már frissítve lett upstreamen, 

https://github.com/barion/barion-web-php/commit/20c6505debf72a08ec540d5e56f474eab40b4390

de gyors tűzoltáshoz ki lehet kapcsolni a beégetett cert használatát a következő fájlban a 4. paraméter "false"-re állításával:

https://github.com/szelpe/woocommerce-barion/blob/af20b6a4dc7a78356370529b4228cfd1652a129b/class-wc-gateway-barion.php#L77

**Comment by oaron** [comment]
Köszi a jelzést, javítottam. Kiment frissítésként.
